name: Invariants

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  invariants:
    permissions:
      contents: read
    uses: ./.github/workflows/gate.yml
    secrets:
      envPAT: ${{ secrets.PAT }}
